"""empty message

Revision ID: 62db00b61df7
Revises: 8848ad89fc05
Create Date: 2022-10-30 13:57:12.509584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62db00b61df7'
down_revision = '8848ad89fc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_type_item', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_type_item'),
    sa.UniqueConstraint('name_type_item')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=True),
    sa.Column('fk_id_type_item', sa.Integer(), nullable=True),
    sa.Column('fk_id_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_id_type_item'], ['type_item.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_id_item'),
    sa.UniqueConstraint('fk_id_item')
    )
    op.drop_table('favorite_character')
    op.drop_table('favorite_planet')
    op.add_column('character', sa.Column('fk_type_item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'type_item', ['fk_type_item'], ['id'])
    op.add_column('planet', sa.Column('fk_type_item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'type_item', ['fk_type_item'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'fk_type_item')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'fk_type_item')
    op.create_table('favorite_planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_planet', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_planet'], ['planet.id'], name='favorite_planet_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='favorite_planet_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('favorite_character',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_character', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_character'], ['character.id'], name='favorite_character_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='favorite_character_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorite')
    op.drop_table('type_item')
    # ### end Alembic commands ###
