"""empty message

Revision ID: 67ac6c61ea52
Revises: d14e9381011d
Create Date: 2022-10-29 14:07:49.735559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ac6c61ea52'
down_revision = 'd14e9381011d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol'),
    sa.UniqueConstraint('rol')
    )
    op.create_table('pet_caregiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('fk_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_caregiver')
    op.drop_table('rol')
    # ### end Alembic commands ###
