"""empty message

Revision ID: 706aee17548e
Revises: 2b86f01c1b62
Create Date: 2022-10-30 14:56:29.534721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '706aee17548e'
down_revision = '2b86f01c1b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.drop_column('character', 'fk_type_item')
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'fk_type_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('fk_type_item', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'type_item', ['fk_type_item'], ['id'])
    op.add_column('character', sa.Column('fk_type_item', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('character_ibfk_1', 'character', 'type_item', ['fk_type_item'], ['id'])
    # ### end Alembic commands ###
