"""empty message

Revision ID: e7ca0639fe1e
Revises: 706aee17548e
Create Date: 2022-10-31 00:37:28.642399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ca0639fe1e'
down_revision = '706aee17548e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('fk_type_item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'type_item', ['fk_type_item'], ['id'])
    op.add_column('planet', sa.Column('fk_type_item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'type_item', ['fk_type_item'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'fk_type_item')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'fk_type_item')
    # ### end Alembic commands ###
